<!--Footer for every page. Provides a default layout-->
            </div> <!--Closes Main content column-->
        </div> <!--Closes main content row (defined in header)-->
        <div class="row">  <!--Creates footer div-->
            <div id="footer" class="col-12"> <!-- Footer is always width of users screen-->

            </div> <!--Closes footer column-->
        </div> <!--Closes footer row -->
    </div> <!--Closes container -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> <!--Gets bootstrap js-->
    </body>
</html>