<!DOCTYPE html>
<!--Header for all webpages on site. Provides just the header, including stylesheets required for webpage.-->
<!-- All views must load this first, followed by any specific stylesheets, then load header_content.phtml-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width initial-scale=1.0">
    <title><?php echo $view->pageTitle ?></title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!--Gets main bootstap css file-->
    <link rel="stylesheet" href="css/my-style.css"  > <!--Gets my-style css file-->

