<?php require_once("Template/header.phtml"); //Gets header
require_once("Template/header_content.phtml");?>
<!-- Main content here -->
<h1 class="first_msg">Matching Results</h1>
<?php require_once("Views/basic_user_info.phtml") ?> <!--Pulls 25 users, showing basic user info-->

<?php require_once ("Views/user_results_nav.phtml") ?> <!-- Provides navigation buttons -->

<?php require_once ("Template/footer.phtml"); //Gets footer ?>



