<?php require_once("Template/header.phtml"); //Gets header
require_once("Template/header_content.phtml");?>
<!-- Main content here -->

<!--Displays some users -->

<?php    if(!isset($_SESSION['uID'])) { ?>
    <h2>Please login to use this page</h2>
<?php  }
else {
    if($view->userData == false) {?>
        <h1 class="first_msg">User not found</h1>
    <?php }else{ ?>
        <h1>User Details</h1>
        <div id="user" class="user_Info"> <!--Displays user info-->

            <img src="<?php
            $target_file="images/".$_GET['selectedID'].".png"; //If user has sent an image, show image. Otherwise, user placeholder
            if(file_exists($target_file)) {
                echo $target_file;
            }
            else{
                echo "images/Img-Placeholder.png";
            }?>" width="100" height="100" alt="userImg.png"> <!--User image - Currently placeholder -->
            <p>UserID: <?php echo $_GET['selectedID'] ?><p>
            <p>Username: <?php echo $view->userData->getUsername() ?> </p>
            <p>Name: <?php echo $view->userData->getFirstName() ?> <?php echo $view->userData->getSurname() ?> </p>
            <p>Date of Birth (DD/MM/YYYY): <?php echo $view->userData->getDob() ?> </p>
            <p>Gender: <?php echo $view->userData->getGender() ?> </p>
            <p>Country: <?php echo $view->userData->getCountry() ?> </p>

            <?php if($_SESSION['uID'] == $_GET['selectedID']) { ?> <!-- If selected user is themselves-->
                <h3>This is your profile</h3>
                <h4>To change your profile image, please use the form below:</h4>
                <form method="post" action=""" enctype="multipart/form-data">
                    <input type="file" id="fileToUpload" name="fileToUpload">
                    <input type="submit" id="uploadImage" name="uploadImage">
                    <input type="text" id="selectedID" name="selectedID" value="<?php echo $_SESSION['uID'] ?>" hidden="hidden" >
                </form>
                <?php if(isset($view->pictureValid)) {
                        if($view->pictureValid == false) { ?>
                        <p>The chosen file was an invalid image</p>

                <?php }}?>
            <?php }else{
                 if($view->friendship == false) { ?> <!--Displays the status of their friendship, and provides the corresponding button to change friendship -->
                <h3>You are not friends with this user</h3>
                     <form method="post" action="">
                         <input type="submit" name="send_fr_req" id="send_fr_feq" value="Send Friend Request">
                         <input type="text" name="targetedUserID" id="targetedUserID" value="<?php echo $_GET['selectedID']?>" hidden="hidden">
                     </form>
            <?php } elseif($view->friendship == 1){ ?>
                <h3>You have sent a friend request to this user</h3>
                     <form method="post" action="">
                         <input type="submit" name="rem_fr" id="rem_fr" value="Cancel Friend Request">
                         <input type="text" name="targetedUserID" id="targetedUserID" value="<?php echo $_GET['selectedID']?>" hidden="hidden">
                     </form>
            <?php }elseif($view->friendship ==2){ ?>
                <h3>You have a pending friend request from this user</h3>
                     <form method="post" action="">
                         <input type="submit" name="acc_fr_req" id="acc_fr_feq" value="Accept Friend Request">
                         <input type="submit" name="rem_fr" id="rem_fr" value="Decline Friend Request">
                         <input type="text" name="targetedUserID" id="targetedUserID" value="<?php echo $_GET['selectedID']?>" hidden="hidden">
                     </form>
            <?php }elseif ($view->friendship == 3) { ?>
                <h3>You are friends with this user</h3>
                     <form method="post" action="">
                         <input type="submit" name="rem_fr" id="rem_fr" value="Remove Friend">
                         <input type="text" name="targetedUserID" id="targetedUserID" value="<?php echo $_GET['selectedID']?>" hidden="hidden">
                     </form>
            <?php }} ?>


        </div>

<?php }} ?>




<?php require_once ("Template/footer.phtml"); //Gets footer ?>



